KrizzShop/Controllers/ApplicationTypeController.cs
using KrizzShop_DataAccess.Repository.IRepository;
using KrizzShop_Models;
using KrizzShop_Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace KrizzShop.Controllers
{
    [Authorize(Roles = WC.AdminRole)]
    public class ApplicationTypeController : Controller
    {
        private readonly IApplicationTypeRepository _repo;
        public ApplicationTypeController(IApplicationTypeRepository repo)
        {
            _repo = repo;
        }

        [HttpGet]
        public IActionResult Index()
        {
            IEnumerable<ApplicationType> objList = _repo.GetAll();
            return View(objList);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ApplicationType applicationType)
        {
            _repo.Add(applicationType);
            _repo.Save();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id is null || id == 0)
                return NotFound();

            var appType = _repo.Find(id.GetValueOrDefault());

            if (appType is null)
                return NotFound();

            return View(appType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ApplicationType applicationType)
        {
            if (!ModelState.IsValid)
                return View(applicationType);

            _repo.Update(applicationType);
            _repo.Save();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if(id is null || id == 0)
                return NotFound();

            var appType = _repo.Find(id.GetValueOrDefault());  

            if(appType is null)
                return NotFound();
            
            return View(appType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int id)
        {
            var appType = _repo.Find(id);

            if(appType == null)
                return NotFound();

            _repo.Remove(appType);
            _repo.Save();

            return RedirectToAction(nameof(Index));
        }

    }
}

KrizzShop/Views/ApplicationType/Create.cshtml
@model KrizzShop_Models.ApplicationType

<form method="post" asp-controller="ApplicationType" asp-action="Create" asp-antiforgery="true">
    <div class="border p-3">
       <div class="form-group row">
           <h2 class="text-info pl-3">Add Application Type</h2>
       </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>
</form>

KrizzShop/Views/ApplicationType/Delete.cshtml
@model KrizzShop_Models.ApplicationType

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border p-3">

        <div class="form-group row">
            <h2 class="text-info pl-3">Delete Application Type</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" disabled class="form-control" />
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>

@section Scripts {

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

KrizzShop/Views/ApplicationType/Edit.cshtml
@model KrizzShop_Models.ApplicationType

<form method="post">
    <input asp-for="Id" hidden />
    <div class="border p-3">

        <div class="form-group row py-2">
            <h2 class="text-info pl-3">Edit Application Type</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>

@section Scripts {

    @{
        <partial name="_ValidationScriptsPartial" />
    }

}

KrizzShop/Views/ApplicationType/Index.cshtml
@model IEnumerable<KrizzShop_Models.ApplicationType>

<div class="container p-3 bg-light">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Application Type List</h2>
        </div>
        <div class="col-6 text-right">
            <a class="btn btn-primary" asp-action="Create" asp-controller="ApplicationType">
                <i class="fas fa-plus"></i>&nbsp; Create New Application Type
            </a>
        </div>
    </div>

    <br />
    <br />

    @if(Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Application Type Name</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach(var obj in Model)
                {
                    <tr>
                        <td width="80%">@obj.Name</td>
                        <td class="text-center">
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="ApplicationType" asp-route-Id="@obj.Id" asp-action="Edit" class="btn btn-primary mx-2">
                                    <i class="fas fa-edit"></i>
                                </a>
                                <a asp-controller="ApplicationType" asp-route-Id="@obj.Id" asp-action="Delete" class="btn btn-danger mx-2">
                                    <i class="far fa-trash-alt"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No application type exists.</p>
    }

</div>